EXTENSION_MAPPING = {
    ".tab": [
        ".dat",
        ".DAT",
        ".map",
        ".MAP",
        ".ID",
        ".id",
        ".IND",
        ".ind",
    ],
    ".TAB": [
        ".dat",
        ".DAT",
        ".map",
        ".MAP",
        ".ID",
        ".id",
        ".IND",
        ".ind",
    ],
    ".shp": [
        ".shx",
        ".SHX",
        ".dbf",
        ".DBF",
        ".prj",
        ".PRJ",
    ],
    ".SHP": [
        ".shx",
        ".SHX",
        ".dbf",
        ".DBF",
        ".prj",
        ".PRJ",
    ],
    ".mif": [
        ".mid",
        ".MID",
    ],
    ".MIF": [
        ".mid",
        ".MID",
    ],
}
MAIN_EXTENSIONS = [".tab", ".TAB", ".shp", ".SHP", ".mif", ".MIF"]
AUX_EXTENSIONS = [
    ".dat",
    ".DAT",
    ".map",
    ".MAP",
    ".ID",
    ".id",
    ".IND",
    ".IND",
    ".shx",
    ".SHX",
    ".dbf",
    ".DBF",
    ".prj",
    ".PRJ",
    ".mid",
    ".MID",
]
